### ISSUE TITLE
It don't respect logging config. I didn't get how to configure alog

### ISSUE THREAD

**Issue by Savier** [keitheis/alog#17]
Following don't write to debug.log:

```
import logging.config
import yaml

logging.config.dictConfig(yaml.load('''
version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout
    
    logfile:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: debug.log
        maxBytes: 10485760
        backupCount: 99
        encoding: utf-8
loggers:
    urllib3:
        level: INFO
        
root:           
    level: DEBUG
    handlers: [console, logfile]
'''))

import alog

alog.warning('I want to write to debug.log!')
```

**Comment by keitheis** [comment]
@Savier thanks for the feedback! Before I figure out a better direction to respect root logging, you may want to try this?
```python
import logging.config
import yaml

import alog


logging.config.dictConfig(yaml.load('''
version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout

    logfile:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: debug.log
        maxBytes: 10485760
        backupCount: 99
        encoding: utf-8
loggers:
    urllib3:
        level: INFO

alog:
    level: DEBUG
    handlers: [console, logfile]
'''))

alog.warning('I want to write to debug.log!')
```

**Comment by keitheis** [comment]
@Savier I think it can be done by
```yaml
...
loggers:
    root:
        level: DEBUG
        handlers: [console, logfile]
    alog:
        level: DEBUG
        handlers: [console, logfile]
```
Lets close this issue.

**Comment by keitheis** [comment]
@Savier I think it can be done by
```yaml
...
loggers:
    root:
        level: DEBUG
        handlers: [console, logfile]
    alog:
        level: DEBUG
        handlers: [console, logfile]
```
Lets close this issue.

**Comment by keitheis** [comment]
@Savier I think it can be done by
```yaml
...
loggers:
    root:
        level: DEBUG
        handlers: [console, logfile]
    alog:
        level: DEBUG
        handlers: [console, logfile]
```
Lets close this issue.

**Comment by Savier** [comment]
Sorry for late answer, but solution doesn't work. I copy-pasted your code to testlog.py ran it and got empty debug.log and default alog formatting on console.

**Comment by nageebt** [comment]
Having the same issue.  I can get python errors & warnings to write to the log file, however anything generated by alog is not written.

Here is my yaml:

```
            version: 1
            disable_existing_loggers: False
            formatters:
                simple:
                    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
            handlers:
                console:
                    class: logging.StreamHandler
                    level: DEBUG
                    formatter: simple
                    stream: ext://sys.stdout

                file:
                    class: logging.handlers.RotatingFileHandler
                    level: DEBUG
                    formatter: simple
                    filename: ../logs/daemon.log
                    maxBytes: 100000
                    backupCount: 20
                    encoding: utf-8
            loggers:
                alog:
                    level: DEBUG
                    handlers: [console, file]
            root:
                level: WARNING
                handlers: [console, file]

```
